import 'package:flutter/material.dart';

import '../../../../app/router/munasakna_routes.dart';
import '../../../../core/enums/munasakna_service_key.dart';

class MunasaknaService {
  const MunasaknaService({
    required this.key,
    required this.titleAr,
    required this.icon,
    required this.route,
    this.subtitleAr,
    this.isImportant = false,
  });

  final MunasaknaServiceKey key;
  final String titleAr;
  final String? subtitleAr;
  final IconData icon;
  final String route;
  final bool isImportant;
}

const List<MunasaknaService> munasaknaInitialServices = [
  MunasaknaService(
    key: MunasaknaServiceKey.profile,
    titleAr: 'بياناتي',
    subtitleAr: 'ملف محلي للحاج',
    icon: Icons.badge_outlined,
    route: MunasaknaRoutes.profile,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.journey,
    titleAr: 'رحلتي',
    subtitleAr: 'مراحل السفر والمناسك',
    icon: Icons.route_outlined,
    route: MunasaknaRoutes.journey,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.dailyCompanion,
    titleAr: 'رفيق اليوم',
    subtitleAr: 'ماذا أفعل الآن؟',
    icon: Icons.today_outlined,
    route: MunasaknaRoutes.dailyCompanion,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.hajjType,
    titleAr: 'نوع الحج والنية',
    subtitleAr: 'تمتع، قران، إفراد',
    icon: Icons.fact_check_outlined,
    route: MunasaknaRoutes.hajjType,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.miqat,
    titleAr: 'المواقيت الشرعية',
    subtitleAr: 'زمانية ومكانية',
    icon: Icons.flag_outlined,
    route: MunasaknaRoutes.miqat,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.fieldGuide,
    titleAr: 'الدليل المكاني',
    subtitleAr: 'مكة والمشاعر',
    icon: Icons.map_outlined,
    route: MunasaknaRoutes.fieldGuide,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.offlineLibrary,
    titleAr: 'المكتبة دون إنترنت',
    subtitleAr: 'محتوى آمن عند ضعف الشبكة',
    icon: Icons.offline_pin_outlined,
    route: MunasaknaRoutes.offlineLibrary,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.hajjSchedule,
    titleAr: 'تقويم الحج',
    subtitleAr: 'مواقيت ومراحل زمنية',
    icon: Icons.event_note_outlined,
    route: MunasaknaRoutes.hajjSchedule,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.documentsWallet,
    titleAr: 'محفظة الوثائق',
    subtitleAr: 'جواز، تطعيمات، تصريح',
    icon: Icons.folder_copy_outlined,
    route: MunasaknaRoutes.documentsWallet,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.groupSupervisor,
    titleAr: 'مجموعتي والمشرف',
    subtitleAr: 'مرشد، مشرف، نقاط تجمع',
    icon: Icons.groups_2_outlined,
    route: MunasaknaRoutes.groupSupervisor,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.accommodationTransport,
    titleAr: 'السكن والنقل',
    subtitleAr: 'الفندق، المخيم، الحافلة',
    icon: Icons.hotel_outlined,
    route: MunasaknaRoutes.accommodationTransport,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.accessibilitySupport,
    titleAr: 'دعم كبار السن والمرضى',
    subtitleAr: 'سلامة ومساعدة سريعة',
    icon: Icons.accessible_forward_outlined,
    route: MunasaknaRoutes.accessibilitySupport,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.postHajj,
    titleAr: 'ما بعد الحج',
    subtitleAr: 'استبيان، متابعة، سجل الرحلة',
    icon: Icons.volunteer_activism_outlined,
    route: MunasaknaRoutes.postHajj,
  ),

  MunasaknaService(
    key: MunasaknaServiceKey.appGuide,
    titleAr: 'دليل التطبيق الشامل',
    subtitleAr: 'مرجع استخدام كل المراحل',
    icon: Icons.menu_book_outlined,
    route: MunasaknaRoutes.appGuide,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.phaseNavigator,
    titleAr: 'مركز المراحل',
    subtitleAr: 'الزمان والمكان والإجراء',
    icon: Icons.hub_outlined,
    route: MunasaknaRoutes.phaseNavigator,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.travelBag,
    titleAr: 'حقيبتي للحج',
    subtitleAr: 'قائمة تجهيز عملية',
    icon: Icons.luggage_outlined,
    route: MunasaknaRoutes.travelBag,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.knowledgeGovernance,
    titleAr: 'حوكمة المعرفة',
    subtitleAr: 'إجابات آمنة بلا فتوى',
    icon: Icons.verified_user_outlined,
    route: MunasaknaRoutes.knowledgeGovernance,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.nusukReadiness,
    titleAr: 'جاهزية نسك',
    subtitleAr: 'الربط المستقبلي الآمن',
    icon: Icons.cloud_sync_outlined,
    route: MunasaknaRoutes.nusukReadiness,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.betaReadiness,
    titleAr: 'جاهزية بيتا',
    subtitleAr: 'تثبيت UX وعقود نسك',
    icon: Icons.workspace_premium_outlined,
    route: MunasaknaRoutes.betaReadiness,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.betaReview,
    titleAr: 'مراجعة الصفحات',
    subtitleAr: 'تدقيق UX والبيانات والاعتماد',
    icon: Icons.fact_check_outlined,
    route: MunasaknaRoutes.betaReview,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.betaTestScenarios,
    titleAr: 'سيناريوهات بيتا',
    subtitleAr: 'اختبار الرحلة قبل النشر',
    icon: Icons.science_outlined,
    route: MunasaknaRoutes.betaTestScenarios,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.nusukContracts,
    titleAr: 'عقود نسك',
    subtitleAr: 'ملف الحاج والرحلة والشكاوى',
    icon: Icons.cloud_sync_outlined,
    route: MunasaknaRoutes.nusukContracts,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.betaPilot,
    titleAr: 'تشغيل بيتا الداخلي',
    subtitleAr: 'خطة اختبار دون بيانات حقيقية',
    icon: Icons.rocket_launch_outlined,
    route: MunasaknaRoutes.betaPilot,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.betaFeedback,
    titleAr: 'سجل ملاحظات بيتا',
    subtitleAr: 'تصنيف UX والمحتوى والصوت',
    icon: Icons.feedback_outlined,
    route: MunasaknaRoutes.betaFeedback,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.releaseGates,
    titleAr: 'بوابات الإطلاق الداخلي',
    subtitleAr: 'اختبارات، خصوصية، اعتماد، نسك',
    icon: Icons.rule_folder_outlined,
    route: MunasaknaRoutes.releaseGates,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.betaClosureChecklist,
    titleAr: 'قائمة إغلاق بيتا',
    subtitleAr: 'بوابات الإغلاق قبل الاختبار',
    icon: Icons.assignment_turned_in_outlined,
    route: MunasaknaRoutes.betaClosureChecklist,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.storeReadiness,
    titleAr: 'جاهزية المتاجر والويب',
    subtitleAr: 'Android وiOS وWeb',
    icon: Icons.storefront_outlined,
    route: MunasaknaRoutes.storeReadiness,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.contentApprovalQueue,
    titleAr: 'اعتماد المحتوى',
    subtitleAr: 'شرعي وصحي وإداري',
    icon: Icons.verified_user_outlined,
    route: MunasaknaRoutes.contentApprovalQueue,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.qualityRiskRegister,
    titleAr: 'مخاطر الجودة',
    subtitleAr: 'سجل حي لبيتا',
    icon: Icons.health_and_safety_outlined,
    route: MunasaknaRoutes.qualityRiskRegister,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.uiConsistencySweep,
    titleAr: 'توحيد الواجهة',
    subtitleAr: 'مسح بصري للصفحات الداخلية',
    icon: Icons.dashboard_customize_outlined,
    route: MunasaknaRoutes.uiConsistencySweep,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.assistantSafetyHardening,
    titleAr: 'أمان المساعد والصوت',
    subtitleAr: 'لا فتوى ولا هلوسة',
    icon: Icons.record_voice_over_outlined,
    route: MunasaknaRoutes.assistantSafetyHardening,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.faqExpansionApproval,
    titleAr: 'توسيع الأسئلة',
    subtitleAr: 'زمني ومكاني واعتماد شرعي',
    icon: Icons.quiz_outlined,
    route: MunasaknaRoutes.faqExpansionApproval,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.nusukBridgeMock,
    titleAr: 'نسك التجريبي',
    subtitleAr: 'طبقة ربط Mock بلا تسجيل',
    icon: Icons.cloud_sync_outlined,
    route: MunasaknaRoutes.nusukBridgeMock,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.stageReminders,
    titleAr: 'تذكيرات المراحل',
    subtitleAr: 'تنبيهات حسب الزمان والمكان',
    icon: Icons.notifications_active_outlined,
    route: MunasaknaRoutes.stageReminders,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.platformReadiness,
    titleAr: 'جاهزية المنصات',
    subtitleAr: 'Web وAndroid وiOS',
    icon: Icons.devices_outlined,
    route: MunasaknaRoutes.platformReadiness,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.betaContentUxAudit,
    titleAr: 'تدقيق المحتوى والواجهة',
    subtitleAr: 'مراجعة صفحة بصفحة قبل الربط',
    icon: Icons.rate_review_outlined,
    route: MunasaknaRoutes.betaContentUxAudit,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.nusukIntegrationHandoff,
    titleAr: 'تقرير نسك للتكامل',
    subtitleAr: 'متطلبات الانضمام والربط',
    icon: Icons.integration_instructions_outlined,
    route: MunasaknaRoutes.nusukIntegrationHandoff,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.finalBetaSmoke,
    titleAr: 'دخان بيتا النهائي',
    subtitleAr: 'اختبارات وتوريث قبل الاعتماد',
    icon: Icons.check_circle_outline,
    route: MunasaknaRoutes.finalBetaSmoke,
    isImportant: true,
  ),

  MunasaknaService(
    key: MunasaknaServiceKey.rituals,
    titleAr: 'دليل المناسك',
    subtitleAr: 'حج وعمرة خطوة بخطوة',
    icon: Icons.explore_outlined,
    route: MunasaknaRoutes.rituals,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.hajjMatrix,
    titleAr: 'مصفوفة الحج v6',
    subtitleAr: 'الطبقات السبع للحج',
    icon: Icons.account_tree_outlined,
    route: MunasaknaRoutes.hajjMatrix,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.hajjFaq,
    titleAr: 'أسئلة الحج',
    subtitleAr: 'حسب الزمان والمكان',
    icon: Icons.quiz_outlined,
    route: MunasaknaRoutes.hajjFaq,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.notifications,
    titleAr: 'الإشعارات والتنبيهات',
    subtitleAr: 'تذكيرات حسب المرحلة',
    icon: Icons.notifications_active_outlined,
    route: MunasaknaRoutes.notifications,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.hajjAssistant,
    titleAr: 'المساعد الصوتي',
    subtitleAr: 'تذكير وتنبيه وقراءة آمنة',
    icon: Icons.smart_toy_outlined,
    route: MunasaknaRoutes.hajjAssistant,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.layerGuide,
    titleAr: 'الدليل الطبقي',
    subtitleAr: 'شرعي، زمني، مكاني، صحي',
    icon: Icons.layers_outlined,
    route: MunasaknaRoutes.layerGuide,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.checklist,
    titleAr: 'قائمة الجاهزية',
    subtitleAr: 'وثائق وحقيبة وتنبيهات',
    icon: Icons.checklist_rtl_outlined,
    route: MunasaknaRoutes.checklist,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.guidance,
    titleAr: 'مواعظ وأحكام',
    subtitleAr: 'محتوى إرشادي مختصر',
    icon: Icons.menu_book_outlined,
    route: MunasaknaRoutes.guidance,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.fatwa,
    titleAr: 'اللجنة الشرعية',
    subtitleAr: 'أسئلة شائعة',
    icon: Icons.gavel_outlined,
    route: MunasaknaRoutes.fatwa,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.health,
    titleAr: 'الصحة والسلامة',
    subtitleAr: 'إرشادات طبية وميدانية',
    icon: Icons.health_and_safety_outlined,
    route: MunasaknaRoutes.health,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.emergency,
    titleAr: 'الطوارئ',
    subtitleAr: 'مساعدة سريعة',
    icon: Icons.emergency_share_outlined,
    route: MunasaknaRoutes.emergency,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.complaints,
    titleAr: 'الشكاوى والملاحظات',
    subtitleAr: 'مرجع محلي للمتابعة',
    icon: Icons.support_agent_outlined,
    route: MunasaknaRoutes.complaints,
    isImportant: true,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.survey,
    titleAr: 'استبيان التجربة',
    subtitleAr: 'تقييم الخدمات',
    icon: Icons.fact_check_outlined,
    route: MunasaknaRoutes.survey,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.contacts,
    titleAr: 'هواتف ضرورية',
    subtitleAr: 'المشرف والطوارئ',
    icon: Icons.contact_phone_outlined,
    route: MunasaknaRoutes.contacts,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.prayerTimes,
    titleAr: 'مواقيت الصلاة',
    subtitleAr: 'تنظيم اليوم',
    icon: Icons.access_time_outlined,
    route: MunasaknaRoutes.prayerTimes,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.currentLocation,
    titleAr: 'موقعي الحالي',
    subtitleAr: 'إحداثيات عند الطلب',
    icon: Icons.my_location_outlined,
    route: MunasaknaRoutes.currentLocation,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.digitalCard,
    titleAr: 'بطاقتي الرقمية',
    subtitleAr: 'QR محلي آمن',
    icon: Icons.qr_code_2_outlined,
    route: MunasaknaRoutes.digitalCard,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.usefulLinks,
    titleAr: 'روابط مفيدة',
    subtitleAr: 'مصادر ومراجع',
    icon: Icons.language_outlined,
    route: MunasaknaRoutes.usefulLinks,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.updateProfile,
    titleAr: 'تحديث بياناتي',
    subtitleAr: 'طلب محلي',
    icon: Icons.manage_accounts_outlined,
    route: MunasaknaRoutes.updateProfile,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.settings,
    titleAr: 'الإعدادات',
    subtitleAr: 'المظهر والخدمات',
    icon: Icons.tune_outlined,
    route: MunasaknaRoutes.settings,
  ),
  MunasaknaService(
    key: MunasaknaServiceKey.privacy,
    titleAr: 'الخصوصية',
    subtitleAr: 'محلي وآمن',
    icon: Icons.privacy_tip_outlined,
    route: MunasaknaRoutes.privacy,
  ),
];
